image:
  tag: v1.0.1

args:
  - run
  - --console
  - --observe
  - /integrations/demo.camel.yaml

extraVolumes:
  - name: integrations
    configMap:
      name: camel-routes-cm
     
extraVolumeMounts:
  - name: integrations
    mountPath: /integrations

