image:
  repository: apache/camel-jbang
  tag: 4.11.0

args:
  - run
  - --console
  - --observe
  - /integrations/demo.camel.yaml

extraVolumes:
  - name: integrations
    configMap:
      name: camel-routes-cm
     
extraVolumeMounts:
  - name: integrations
    mountPath: /integrations

