apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: jbang-camel-demo-devt
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - devt-values.yaml
    path: .
    repoURL: https://github.com/rmortale/camel-helmet-demo.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
