apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: jbang-camel-demo
  namespace: argocd
spec:
  generators:
    - clusters:
         selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: 'jbang-camel-demo-{{name}}'
      namespace: argocd
    spec:
      project: default
      sources:
        - repoURL: https://github.com/rmortale/camel-helmet-demo.git
          path: .
          targetRevision: main
          helm:
            valueFiles:
              - {{name}}-values.yaml
      destination:
        server: '{{server}}'
        namespace: k8scc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
